- package.json
- src/angular2-drag-scroll.ts
Fix for #2 
Removed BrowserModule inside angular2-drag-scroll.ts
> Remove BrowserModule from the library

- src/tsconfig.json
https://github.com/bfwg/angular2-drag-scroll/issues/5
Explain what you did.
- Turn source map to true"
> Turn source map on

- angular-cli.json
- demo/app/app.module.ts
- demo/test.ts
- karma.conf.js
- package.json
- src/angular2-drag-scroll.spec.ts
> Update to angular4

- package.json
- src/angular2-drag-scroll.ts
> fix(mousedowan) remove preventDefault

- demo/app/home/home.component.ts
- demo/index.html
- src/angular2-drag-scroll.ts
Fix the bug where button click is not working in device view.
Relates to #26 #20 #21
> fix(device): fix drag scroll not working in mobile view

- README.md
- demo/app/angular2-drag-scroll.spec.ts
- demo/app/home/home.component.css
- demo/app/home/home.component.html
- demo/app/home/home.component.ts
- package.json
- src/angular2-drag-scroll.ts
- add ablitiy to snap item when navigating.
- add ablitiy to snap item when scrolling.
- add ablitiy to snap item when draging.
> feat: improve nav buttons

- README.md
- demo/app/home/home.component.ts
- index.metadata.json
- package.json
- src/angular2-drag-scroll.ts
- Fix the bug where using touch, you can't scroll all the way right, you have to click the button to get it to snap to the last image
- Fix the bug where clicking the nav buttons rapidly has no effect, you have to wait for each animation to finish.
- Fix the bug where weird issue where the nav buttons won't be disabled, even with one image in the carousel.
> Fix snap bug

- demo/app/angular2-drag-scroll.spec.ts
- package.json
- src/angular2-drag-scroll.ts
- Fix a bug where the wrapper width is not copied from directive
element.
> Fix warpper style issue

- package.json
- src/angular2-drag-scroll.ts
- fix a bug where resize will break issue
> More bug fix

- package.json
- src/angular2-drag-scroll.ts
- fix a bug where the navigation button status is not getting setup
properly when adding a new item.
> navigation button status bug fix

- README.md
- demo/app/home/home.component.html
- src/angular2-drag-scroll.ts
> Ability to disable snap

- demo/app/app-routing.module.ts
- src/angular2-drag-scroll.ts
tslint reports the following issues:
```bash
ERROR:  ../angular2-drag-scroll/src/angular2-drag-scroll.ts[432, 19]: variable 'easeInOutQuad' used before declaration
ERROR: ../angular2-drag-scroll/demo/app/app-routing.module.ts[14, 10]: missing whitespace
```
Fix in.
> fix tslint issues

- demo/app/app.module.ts
- demo/app/home/home.component.css
- demo/app/home/home.component.html
- package.json
It would be useful to normalize the layout to use angular/flex-layout as much as possible and get rid of custom css / media queries as appropriate. 
Injecting FlexLayoutModule in the code and replacing one custom css for the moment.
> Flex layout

- demo/app/angular2-drag-scroll.spec.ts
- demo/app/home/home.component.ts
Replace renderer with renderer2 .  Files missed during the earlier iteration in Issue #60 . Added now. FYI
> renderer to renderer2

- CHANGELOG.md
Initial Version of changelog with varying sizes of headers  for major, minor and release versions
> Initial Version of changelog with varying sizes of headers 

- package-lock.json
This reduces build time significantly as part of CI process after commits.
> package-lock.json to be checked in

- CHANGELOG.md
- package.json
> Remove incorrect package.json package from package.json

- CHANGELOG.md
- package-lock.json
As per changes to package.json in Issue #89 - regenerate package-lock.json as well and check in the latest version
```bash
$ npm i
```
This process needs to be done everytime we make a change in package.json though. FYI
> regnerate package-lock.json as in Issue #89

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
> Replace angular2+ keyword with angular as it is misleading in some case

- CHANGELOG.md
- TODO.md
- package-lock.json
- package.json
- src/ngx-drag-scroll.spec.ts
- src/ngx-drag-scroll.ts
- tslint.json
some of the rules of tslint modified to reflect angular cli 1.6.2 / tslint 5.7.0+
> tslint updated to the defaults as of angular cli 1.6.2 

- CHANGELOG.md
- package-lock.json
- package.json
- src/ngx-drag-scroll.ts
- tslint.json
Some of the options in tslint were flagged to be deprecated. 
Fixing them
> style: tslint fixes

- CHANGELOG.md
- package.json
- src/ngx-drag-scroll.ts
> fix: fix global select text issue

- package-lock.json
Add package-lock.json back, this will fix #124 
fix: add package-lock.json back
> Add package-lock.json back

- CHANGELOG.md
- package-lock.json
- package.json
- src/ngx-drag-scroll.ts
Bug fix
Vertical touch scroll in Android and iOS device will reset the location of the carousel.
Vertical touch scroll in Android and iOS device will not reset the location of the carousel.
NO
> Fix issue 140

- CHANGELOG.md
- package-lock.json
- package.json
- src/ngx-drag-scroll.spec.ts
- src/ngx-drag-scroll.ts
Bug fix
- Window on resize does not affect hide/show scrollbar.
- Scroll content wrapper does not inherit the display style from the component element.
- Window on resizing affect scrollbar hide/show.
- Scroll content wrapper inherits the display style from the component element.
No
> Inheritance for scroll content wrapper display style.

- CHANGELOG.md
- package.json
- src/tsconfig.json
Fix run issue on IE 11
Cannot run on IE 11
Should fix the runtime issue.
NO
> Fix issue on IE 11

- CHANGELOG.md
- package-lock.json
- package.json
- src/ngx-drag-scroll.ts
Closes #171
Fix the issue mention in #171 . 
The currIndex setter gets trigger multiple times and can go over the maximum length.
The currIndex setter will get trigger once only and will not go over limit.
No
> fix: method index changed and move right does not work

- package.json
- [v] The commit message follows our guidelines
- [v] Tests for the changes have been added (for bug fixes / features)
- [v] Docs have been added / updated (for bug fixes / features)
- [v] Unit tests are passing `ng test`
- [v] Lint tests are passing `ng lint`
fix remove warning for npm install
no
no
no
> fix: remove npm install peer dependency warning

- CHANGELOG.md
- demo/app/home/home.component.html
- demo/app/home/home.component.ts
- package.json
- src/ngx-drag-scroll.spec.ts
- src/ngx-drag-scroll.ts
- tslint.json
> Fix: Index change doesn't work

- .gitignore
- src/ngx-drag-scroll-item.ts
- src/ngx-drag-scroll.spec.ts
- src/ngx-drag-scroll.ts
This is a bug fix for projects that have SSR and lazy loading
we have a bug ``document is not defined``
I've replaced the global document on DOCUMENT from Angular
this changes won't break any project
> fix: document is not defined, resolve providers on node for lazy loading

- README.md
- demo/app/home/home.component.html
- demo/app/home/home.component.ts
- src/ngx-drag-scroll.ts
Closes ##185
An new @Output dsInitializated.
dsInitializated will emit when the drag scroll componet is fully initialized.
> feat: add output for ds initialization

- CHANGELOG.md
- README.md
- demo/app/home/home.component.css
- demo/app/home/home.component.html
- package.json
- src/ngx-drag-scroll.spec.ts
- src/ngx-drag-scroll.ts
- [/] The commit message follows our guidelines
- [/] Tests for the changes have been added (for bug fixes / features)
- [/] Docs have been added / updated (for bug fixes / features)
- [/] Unit tests are passing `ng test`
- [/] Lint tests are passing `ng lint`
Feature
User can scroll with mouse wheel only vertically
User can now also scroll with mouse wheel horizontally which improves UX especially when scrollbar is hidden.
* **Does this PR introduce a breaking change?** (What changes might users need to make …
> allow to scroll horizontally with mouse wheel

- CHANGELOG.md
- package.json
- src/ngx-drag-scroll.ts
> Remove debug log

- demo/app/home/home.component.html
- src/ngx-drag-scroll.spec.ts
- src/ngx-drag-scroll.ts
> fix: add a margin to the last item when hide scroll bar

- src/ngx-drag-scroll.ts
Bug fix: Changed HostListener event handlers access modifiers.
[Issue 219](https://github.com/bfwg/ngx-drag-scroll/issues/219)
Angular invokes the supplied handler method when the host element emits the specified event, and updates the bound element with the result.
> fix: cannot compile with aot

- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts
Bug fix
https://github.com/bfwg/ngx-drag-scroll/issues/226
the component will now listen correctly on touch-events and scroll as expected
> fix: issue #226 making drag-scroll work properly with touch-input

- CHANGELOG.md
- projects/ngx-drag-scroll/package.json
- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts
Fix a small bug where the move right button moves more than it should.
Allow working with Angular 8
> feat: allow to work wit angular 8

- CHANGELOG.md
- projects/ngx-drag-scroll/package.json
- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts
- src/app/home/home.component.html
- Fix an issue where dragging on iOS devices moves the carousel faster.
- Fix an edge case in iOS 9 where item with ng-content sometimes has width of 0.
> Fix touch drag on mobile devices

- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts
Resolve the errors in the console for the demo application.
> fix: error in the demo console log

- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts
Fix an issue where the console sometimes gives errors.
> fix: handle first child is undefined issue
