bfwg/ngx-drag-scroll

- src/angular2-drag-scroll.ts
Renderer from angular/core is deprecated. 
```typescript
import {Renderer} from '@angular/core';
```
Replaced by renderer2
> renderer to Renderer2

- package.json
Fixing the following warning: 
```bash
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```
change 'prepublish' to 'prepare'
> prepublish to prepare

- angular-cli.json
- demo/main.ts
- package.json
The browser console reports the following when we load the pages. 
```console
Could not find HammerJS. Certain Angular Material components may not work correctly.
```
Adding gesture support  using hammerjs as well. 
More details here:
https://material.angular.io/guide/getting-started#step-5-gesture-support.
> add hammerjs support

- .npmignore
- CHANGELOG.md
As per  https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325 - distributing .ts seems to be a problem and not the recommended way of doing things (with version incompatibility between typescript versions)
```
"You have TS files in your node_modules. This really goes against how libraries should be packaged: libraries should never ship their source .ts files."
```
Ignore .ts but distribute .d.ts though. 
This seems to address the issue in #69 , (reported again in #72) as well
> do not distribute ts in npm

- CONTRIBUTING.md
Add notes about various types for handy reference before commiting ( as enforced by commitlint )
> docs: notes for future contribution and formatting commit

- CHANGELOG.md
- src/ngx-drag-scroll.ts
- navigation scrolling will now scroll to the correct position when the
width of the elements are different.
Closes #99
> fix: fix stepped scrolling issue

- CHANGELOG.md
- README.md
- TODO.md
- demo/app/home/home.component.html
- demo/app/home/home.component.ts
- package-lock.json
- package.json
- src/ngx-drag-scroll.spec.ts
- src/ngx-drag-scroll.ts
- tslint.json
Fix the following tslint warning.
```console
1. ERROR: /home/travis/build/bfwg/ngx-drag-scroll/src/ngx-drag-scroll.ts[20, 14]: The name of the class DragScroll should end with the suffix Directive (https://angular.io/styleguide#style-02-03)
```
More details at - https://angular.io/styleguide#style-02-03
```console
1. ERROR: /home/travis/build/bfwg/ngx-drag-scroll/src/ngx-drag-scroll.ts[18, 13]: The selector of the directive "DragScroll" should be named camelCase (https://angular.io/styleguide#style-02-06)
```
More details at - https://angular.io/styleguide#style-02-06
> style: The name of the class DragScroll should end with the suffix Directive

- src/ngx-drag-scroll.ts
Fixed bug that caused Firefox to default to drag-and-drop mode when images are click and dragged. Bug originally logged [here](https://github.com/bfwg/ngx-drag-scroll/issues/125).
This was due to browser's default behavior and was fixed by calling `preventDefault();` on the event object of the 'dragstart' event. See MDN reference [here](https://developer.mozilla.org/en-US/docs/Web/Events/dragstart).
I've tested this on the following browsers on Windows 10 (64-bit) without issues:
- Firefox Quantum 59.0.2 (64-bit)
- Google Chrome 65.0.3325.181 (64-bit)
- Internet Explorer 11.309.16299.0
- Microsoft Edge 41.16299.248.0
> fix: firefox default to drag and drop for images bug

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE
- CHANGELOG.md
- package.json
- src/ngx-drag-scroll.ts
- Fix #129 
- Add github templates.
> fix: onMouseUp stops all propagation when selecting text

- README.md
- demo/app/home/home.component.html
- demo/app/home/home.component.ts
- src/ngx-drag-scroll.spec.ts
- src/ngx-drag-scroll.ts
+ feat: event is emitted when snap animation finishes
+ feat: snap animation duration can be set by input binding
feature, docs update
1) It is not possible to know whether the snap animation has already finished. Thus implementing an action after the snap animation has finished can only be done by a workaround, e.g. looking into the source code for the duration and using setTimeOut().
2) The duration of the snap animation is fixed (500ms).
1) When the snap animation finsihes, an event is emitted to notify …
> Notify consumers when snap animation has finished

- README.md
- demo/app/app.module.ts
- demo/app/home/home.component.html
- demo/app/home/home.component.ts
- src/ngx-drag-scroll.ts
**NOTE**: There are 3 tests failing that were failing before any of my changes. I verified this by running the tests on the current develop branch
This PR is for a feature requests to fire an event when the current index changes.
The current behavior is that you can access the currIndex property by referencing the @Child component, however, there is no way to bind or listen for the index changing.
This feature allows developers to subscribe to the (indexChanged) event and get updates on the current idnex when …
> Added EventEmitter for the indexChanged event

- CHANGELOG.md
- package.json
- src/ngx-drag-scroll.ts
- tslint.json
Move left/right does not need to wait for the animation to finish
Move left/right does not work while snap is in animation.
Move left/right does not need to wait for the animation to finish
No
> Move left/right does not need to wait for the animation to finish

- src/ngx-drag-scroll.spec.ts
- src/ngx-drag-scroll.ts
- [n/a] Docs have been added / updated (for bug fixes / features)
Bug fix / feat.
Unnecessary listening to mousemove events on the page.
Bind mousemove events only when mousedown is triggered for that component. Allowing multiple components to be used on the same page without throttling.
Not breaking changes, only a behavior fix.
Some tests that uses …
> feat: bind global handlers (mouseup, mousemove) on mousedown

- CHANGELOG.md
- demo/app/home/home.component.css
- package.json
- src/ngx-drag-scroll.spec.ts
- src/ngx-drag-scroll.ts
- [/] The commit message follows our guidelines
- [/] Tests for the changes have been added (for bug fixes / features)
- [/] Docs have been added / updated (for bug fixes / features)
- [/] Unit tests are passing `ng test`
- [/] Lint tests are passing `ng lint`
Bug fix
When drag-scroll's height changes after component has been initialized (eg. because of media-queries) and scrollbar is hidden, .drag-scroll-wrapper's height does not update along with it.
.drag-scroll-wrapper's dimensions are recalculated after …
> fix: refresh wrapper's dimensions after window resize when scrollbar is hidden

- CHANGELOG.md
- package.json
- src/ngx-drag-scroll.ts
Fix an issue where the toChildrenLocation doesn't go to the right location when the last item has a margin to the right*.
*We add margin-right of the width of the scroll bar to the last item in the carousel when the scroll bar is hidden.
> toChildrenLocation doesn't go to the right location

- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts
Do not forward snap when the item is against the left of the border(scroll left 0).
> fix: forward snap should not happen when the scroll left is 0

- .travis.yml
feature
Travis build fail some times because of xvfb not starting.
Use the newest xenial image dist and enable xvfb as travis service + add chrome addon.
No
> ci: update travis config to latest xenial dist and use xvfb as service

- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.spec.ts
- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts
* **What kind of change does this PR introduce?**
bug fix + code improvements
* **What is the current behavior?**
Currently there is an error in case we do not use `drag-scroll-item` directive after update to latest 7 version of library - same error as in https://github.com/bfwg/ngx-drag-scroll/issues/244
1. added a check on the existence of at least one element of type `DragScrollItemDirective` in method `adjustMarginToLastChild`
```ts
private adjustMarginToLastChild(): void {
if (this._children && this._children.length > 0 && this.hideScrollbar) {
//...
}
}
``` 
2. removed access to private property `_results` of `QueryList`. Mostly replaced with public `length` …
> fix: prevent error in case of empty content or no drag-scroll-item is used

- CHANGELOG.md
- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts
Bug fix for issue #262 
When using ngx-drag-scroll, other HTML5 elements in the same page cannot be dragged.
You can now use other HTML5 draggable elements in the same page as ngx-drag-scroll
No.
I've made this suggestion some time ago but I haven't opened a PR yet. This change has fixed my issue up to now and I believe it could solve the problem for others. This …
> fix: restrict drag action to ngx-drag-scroll component

- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.spec.ts
- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts
Style fix
When setting `[scrollbar-hidden]` to `true` in the template the whole slider disappears. The elements are all present in the DOM but the first direct child of `<drag-scroll>`, namely the element with the classes `drag-scroll-wrapper drag-scroll-container`, has a height of `0` and hence isn't visible.
The element in question will apply a value of `100%` as its `height` if there aren't any pixel values from its dimensions (yet).
* **Does this PR introduce a breaking change?** (What changes might users …
> style: safeguard wrapper height when dimensions are not yet available

- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.spec.ts
- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts
Bug fix
After the window is resized, frst click on an item is not propagated.
In this case, browser sends a "mouseover" between "mousedown" and "mouseup" events; all ​at the same coordinates.
The library transforms them to a "0px scroll" and disable pointer events.
The library ignore "mouseover" event if its coordinates are the same than the previous "mousedown" ones.
No
* **Other …
> fix: pointer events not propagated after window resize

- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts
- [x ] Unit tests are passing `ng test`
- [x ] Lint tests are passing `ng lint`
Bug fix - when direction:rtl style is used (Hebrew in my case) the move functions do not work.
just apply a "direction:rtl" to the style of say the demo page, and you'll see the failed functionality
a quick fix - forcing 'direction:rtl' and flipping the UI did the trick, only thing left was a twirq in position calculation (reversing it) and it did the trick.
* **Does this PR introduce a breaking change?** (What changes might users …
> fix: when direction:rtl style applied, move functions failed to work

- projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts
bug fix
after my last commit to support direction:rtl, Move functions worked but the content got flipped. See I wanted to keep the existing "math" logic and just trick the browser... but the content got flipped. so I removed the flipping code and instead changed the scrollLeft calcs to support negatives (it was just 3 tiny places. rest of commit is actually removing of the old fix).
no
* …
> fix: patch to direction:rtl flipped the content. fixing logic instead
